### ISSUE TITLE
Ruby 1.9.3, Rails 4.2.7.1, stacktrace after bundle update

### ISSUE THREAD

**Issue by SchlauFuchs** [sportngin/okcomputer#120]
```
$ bundle exec rake --tasks                                  rake aborted!
SyntaxError: /home/user/.rvm/gems/ruby-1.9.3-p484/gems/okcomputer-1.11.1/lib/ok_computer/legacy_rails_controller_support.rb:13: syntax error, unexpected tPOW, expecting ')'
    def render(**options, &block)
                 ^
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/okcomputer-1.11.1/lib/ok_computer/legacy_rails_controller_support.rb:18: syntax error, unexpected keyword_end, expecting $end
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/okcomputer-1.11.1/lib/okcomputer.rb:6:in `<top (required)>'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/user/repositories/tracking_notification/config/application.rb:8:in `<top (required)>'
/user/repositories/tracking_notification/Rakefile:5:in `require'
/user/repositories/tracking_notification/Rakefile:5:in `<top (required)>'
/home/user/.rvm/gems/ruby-1.9.3-p484/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'
```
What to do now?

**Comment by chrisarcand** [comment]
We somewhat officially no longer support Ruby 1.9.3. Support for was removed [here](https://github.com/sportngin/okcomputer/pull/92#issuecomment-227432324). 

@pbyrne No major version bump was made with dropping 1.9.3 support, however; any new thoughts on this?

**Comment by pbyrne** [comment]
In retrospect, perhaps a major version bump was warranted when dropping that support. Ruby 1.9 reached end of life [in February 2015](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), so I'm not sure how much effort we want to spend maintaining compatibility. 

That said, I think in this case, I think it's just a matter of tweaking the syntax of our `render` wrapper method to accept `options={}` rather than `**options`. I'll take a peek later today.

In the meantime, you can use an older version of OK Computer to get the app to boot with Ruby 1.9.3. It looks like [the offending code](https://github.com/sportngin/okcomputer/commit/84214f0cdcafafa5944174b0562d4aec3fae42c2) was added in v1.11, so any earlier version should do the trick.

Separate from all of that, though, I'd encourage you to get to a newer version of Ruby sooner than later @SchlauFuchs—both from a quality-of-life standpoint, but also regarding critical security fixes.

**Comment by pbyrne** [comment]
v1.12.0 should work better for you with Ruby 1.9.

**Comment by SchlauFuchs** [comment]
thanks.I suggest to mark the versions on rubygems to require ruby 2.x so
that I would have known :P
