### ISSUE TITLE
Add tips on how to mount OkComputer in a sinatra app

### ISSUE THREAD

**Issue by darrenleeweber** [sportngin/okcomputer#125]
Please add README documentation on how to mount OkComputer in a sinatra app (or any rack app).

**Comment by darrenleeweber** [comment]
Considerations:
- can sinatra run a rails engine?
- can https://github.com/sportngin/okcomputer/blob/master/app/controllers/ok_computer/ok_computer_controller.rb be adapted to a sinatra route (with changes to param handling and response details)?
- can the rack `config.ru` mount the rails engine without using the entire rails gemset?

**Comment by anfleene** [comment]
I assume it can be done similar to the Grape version https://github.com/bellycard/okcomputer-grape

But we don't have official support for running it that way at the moment. We have plans to split okcomputer proper into a few different gems to remove the rails dependency from it's core as well as split out anything more than the basic checks into their own contrib gem so that they can be released independently. This will likely all be part of okcomputer 2.0. But we haven't started on any of this work yet. Once we do we'll update the README with all the necessary details to run okcomputer outside of rails.

**Comment by darrenleeweber** [comment]
One attempt that seems to be working, at some level, is to create a sinatra route similar to the code in the controller (noted above).  For example, using `OkComputer.mount_at = '/status'` in the `config/initializer/okcomputer.rb`, the following quick hack is working in a sinatra app:
```ruby
    get '/status' do
      # TODO: modify route to detect .json format?
      # TODO: modify route to detect specific checks?
      content_type 'text/plain'
      cache_control :none
      begin
        checks = OkComputer::Registry.all
        checks.run
        body checks.to_json # note the lack of CN here
        status checks.success? ? 200 : 500
      rescue StandardError => err
        status 500
        body err.inspect
      end
    end
```

**Comment by anfleene** [comment]
Awesome, glad you got it working!

**Comment by johnnyshields** [comment]
Can this be added to the readme then close this issue?
