### ISSUE TITLE
Proposal: allow running healtchecks in parallel

### ISSUE THREAD

**Issue by sergeyevstifeev** [sportngin/okcomputer#72]
Currently the healthchecks are run in sequence:

    # Public: Run the registry's checks
    def run
      checks.each(&:run)
    end

this presents an issue for us as we have a constantly growing number of healthchecks but we also want to have a fixed known timeout for all healthchecks to be completed. It would be great to allow to run the healthchecks in parallel. What do you think?
I can create a pull request if you think this is a reasonable suggestion.

**Comment by pbyrne** [comment]
This isn't something we've run into with our checks, since we keep the list pretty small. But I think it makes sense to be able to opt into parallel checks (or at least be able to opt out). Since it hasn't been parallelized in the past, I'd hate for someone to get burnt by undiscovered bugs in their checks introduced by running them in parallel.

**Comment by sergeyevstifeev** [comment]
Sounds reasonable :+1:. I'll try to come up with a pull request soon then.
